name: Release Package Version

on:
    push:
        branches:
            - 'master'

jobs:
    run-build-and-test:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                node-version: [18]
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install
            - name: Test Package
              run: pnpm run test
            - name: Build Package
              run: pnpm run build
            - run: echo "previous_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo '')" >> $GITHUB_ENV
            - name: Push to NPM
              run: npm publish --access public
              if: env.previous_tag
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
            - name: Create Tag from package.json
              id: create_tag
              uses: jaywcjlove/create-tag-action@main
              if: env.previous_tag
              with:
                  package-path: ./package.json
